# Generated by Django 4.1 on 2022-08-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_courseinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=512)),
                ("iconClass", models.CharField(max_length=300)),
            ],
        ),
    ]
